//                                                                               
// createTime.H                                                                  
// ~~~~~~~~~~~~                                                                  
                                                                                 
Foam::Info<< "Create time\n" << Foam::endl;                                      
                                                                                 
Foam::Time runTime(controlDict, args); 
